export const START_AUTH_REQUEST ='START_AUTH';
export const AUTH_REQEST_SUCCESS='AUTH_SUCCESS';
export const AUTH_REQUEST_FAILURE='AUTH_FAILURE';
export const AUTH__REQUEST_SEND_AUTH_INFO='AUTH_PROCEEDING';